### ISSUE TITLE
gym.make(gym_id) not working, the env is not registered as a gym env

### ISSUE THREAD

**Issue by BFAnas** [Farama-Foundation/Gym-MicroRTS#81]
Hi,

Is the environment supposed to be automatically registered as a gym env? or should the registry be done manually? Thanks!

**Comment by vwxyzjn** [comment]
The latest version only ships an interface similar to gym. See 

https://github.com/vwxyzjn/gym-microrts/blob/e4e11405a36044eab49d4cd2c2ed084b019bb999/hello_world.py#L10-L19
